[db3306]
title='db3306'
db-servers-hosts="172.16.1.3:3306,172.16.1.4:3306"
db-servers-prefered-master="172.16.1.3:3306"
db-servers-credential="root:luling1012"
replication-credential="repl:luling1012"
failover-mode="manaual"
proxysql=true
proxysql-server="172.16.1.3"
proxysql-port=6033
proxysql-admin-port=6032
proxysql-writer-hostgroup=10
proxysql-reader-hostgroup=11
proxysql-user="admin"
proxysql-password="admin"                                                                                                                                                                                                               
proxysql-bootstrap=false
[Default]
monitoring-datadir="/var/lib/replication-manager"
monitoring-sharedir="/usr/share/replication-manager"
log-level=7
log-file="/var/log/replication-manager.log"
replication-multi-master=false
replication-multi-tier-slave=false
failover-readonly-state=true
http-server=true
http-bind-address="0.0.0.0"
http-port="10001"